#!/usr/bin/env bash
# EXPLAIN baseline (Stage 01, DB-D28/D40) — prove the 5 hottest v1 queries use their
# indexes, not sequential scans, at volume. Builds a throwaway DB, loads synthetic rows,
# ANALYZEs, captures EXPLAIN plans, and writes docs/database/explain-baseline.md.
#
# Config via env (defaults suit the local dev cluster):
#   PGHOST PGPORT PGUSER PGPASSWORD  EXPLAIN_DB=fundslink_explain  PGBIN=/path/to/bin
set -euo pipefail

PGHOST="${PGHOST:-127.0.0.1}"; PGPORT="${PGPORT:-5432}"; PGUSER="${PGUSER:-fundslink}"
EXPLAIN_DB="${EXPLAIN_DB:-fundslink_explain}"
PGBIN_PREFIX="${PGBIN:+$PGBIN/}"
export PGHOST PGPORT PGUSER
PSQL="${PGBIN_PREFIX}psql"
CREATEDB="${PGBIN_PREFIX}createdb"; DROPDB="${PGBIN_PREFIX}dropdb"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOC="$ROOT/docs/database/explain-baseline.md"
URL="postgresql://${PGUSER}@${PGHOST}:${PGPORT}/${EXPLAIN_DB}"

echo "[explain] (re)creating $EXPLAIN_DB ..."
"$DROPDB" --if-exists "$EXPLAIN_DB"; "$CREATEDB" "$EXPLAIN_DB"
( cd "$ROOT/apps/api" && ALEMBIC_DATABASE_URL="$URL" python -m alembic upgrade head >/dev/null )

echo "[explain] loading synthetic volume ..."
"$PSQL" -q -d "$EXPLAIN_DB" <<'SQL'
INSERT INTO "user"(id,email,password_hash,account_state)
  SELECT 'u'||g, g||'@t.test','x','ACTIVE' FROM generate_series(1,5000) g;
INSERT INTO student_profile(id,first_name,last_name,level,field_of_study)
  SELECT 'u'||g,'F','L','UG','CS' FROM generate_series(1,5000) g;
INSERT INTO external_bursary(id,name,provider,level_eligibility,status)
  SELECT 'b'||g,'B','P',ARRAY['UG'],'OPEN' FROM generate_series(1,500) g;
-- 20k applications; (student, year) kept unique to satisfy uq_app_active_per_year
INSERT INTO funding_application(id,student_profile_id,application_type,status,academic_year)
  SELECT 'a'||g,'u'||(1+(g%5000)),'POSTGRAD','SUBMITTED',(2020+(g/5000))::text
  FROM generate_series(1,20000) g;
-- a realistically large review queue (national platform), paginated by the admin UI
UPDATE funding_application SET status='READY_FOR_REVIEW'
  WHERE id IN (SELECT id FROM funding_application ORDER BY id LIMIT 5000);
-- 20k tracked; (g%5000, g/5000) is a unique pair => satisfies uq_tracked_pair
INSERT INTO tracked_application(id,student_profile_id,external_bursary_id)
  SELECT 't'||g,'u'||(1+(g%5000)),'b'||(1+(g/5000)) FROM generate_series(1,20000) g;
INSERT INTO match_result(id,student_profile_id,external_bursary_id,score,model_version,prompt_version)
  SELECT 'm'||g,'u'||(1+(g%5000)),'b'||(1+(g/5000)),0.5,'m1','p1' FROM generate_series(1,20000) g;
-- 60k pending outbox rows for the partial-index claim query
INSERT INTO notification_outbox(id,user_id,trigger,channels,payload,next_attempt_at)
  SELECT 'o'||g,'u'||(1+(g%5000)),'DECISION_APPROVED',ARRAY['email'],'{}',
         now() + ((g%1000)||' seconds')::interval
  FROM generate_series(1,60000) g;
ANALYZE;
SQL

row_count() { "$PSQL" -tA -d "$EXPLAIN_DB" -c "select count(*) from $1"; }
APPS=$(row_count funding_application); TRACKED=$(row_count tracked_application)
MATCHES=$(row_count match_result); OUTBOX=$(row_count notification_outbox)

declare -a TITLES SQLS
TITLES[1]="1. My applications (student dashboard)"
SQLS[1]="SELECT * FROM funding_application WHERE student_profile_id='u123' AND deleted_at IS NULL ORDER BY created_at DESC"
TITLES[2]="2. Dashboard tracked list"
SQLS[2]="SELECT * FROM tracked_application WHERE student_profile_id='u123' AND deleted_at IS NULL ORDER BY last_activity_at DESC"
TITLES[3]="3. Outbox claim (partial index, SKIP LOCKED)"
SQLS[3]="SELECT * FROM notification_outbox WHERE state='PENDING' AND next_attempt_at<=now() ORDER BY next_attempt_at FOR UPDATE SKIP LOCKED LIMIT 100"
TITLES[4]="4. Matches by student"
SQLS[4]="SELECT * FROM match_result WHERE student_profile_id='u123' ORDER BY created_at DESC"
TITLES[5]="5. Review queue (by status, paginated)"
SQLS[5]="SELECT * FROM funding_application WHERE status='READY_FOR_REVIEW' ORDER BY created_at DESC LIMIT 50"

{
  echo "# EXPLAIN Baseline — FundsLink Academy"
  echo ""
  echo "> **DB-D28 / DB-D40.** The 5 hottest v1 queries (TAD §5.3 surface) must use their"
  echo "> indexes — not sequential scans — at volume. Generated by \`scripts/explain_baseline.sh\`."
  echo "> Re-run with \`make explain\`."
  echo ""
  echo "Volume: funding_application=$APPS, tracked_application=$TRACKED, match_result=$MATCHES, notification_outbox=$OUTBOX (PENDING)."
  echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ) · PostgreSQL 16."
  echo ""
  for i in 1 2 3 4 5; do
    echo "## ${TITLES[$i]}"
    echo ""
    echo '```sql'
    echo "${SQLS[$i]};"
    echo '```'
    echo ""
    echo '```'
    "$PSQL" -d "$EXPLAIN_DB" -c "EXPLAIN ${SQLS[$i]}"
    echo '```'
    echo ""
  done
} > "$DOC"

echo "[explain] verifying every plan uses an index (no Seq Scan on the target) ..."
fail=0
for i in 1 2 3 4 5; do
  plan="$("$PSQL" -tA -d "$EXPLAIN_DB" -c "EXPLAIN ${SQLS[$i]}")"
  if echo "$plan" | grep -qi "Index"; then echo "  [OK ] query $i uses an index"; else
    echo "  [FAIL] query $i has NO index scan:"; echo "$plan"; fail=1; fi
done
echo "[explain] doc written: $DOC"
exit $fail
